on: push
name: Build and Publish
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish act-pwsh
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            jgrote/act-pwsh:latest
            ghcr.io/justingrote/act-pwsh:latest
      - name: Build and publish act-pwsh-dotnet
        uses: docker/build-push-action@v2
        with:
          context: ./pwshdotnet
          push: true
          tags: |
            jgrote/act-pwsh-dotnet:latest
            ghcr.io/justingrote/act-pwsh-dotnet:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

